language: node_js
node_js:
  - lts/argon
  - lts/boron
  - stable
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - echo "START=yes" | sudo tee -a /etc/default/beanstalkd > /dev/null
  - sudo service beanstalkd restart
notifications:
  email: false
  slack:
    secure: KTJ8Kpo7mqKmb25HBDAffZT24dL82aQEpSu90sDbYKwdJ2KRqLy0hmu9Irjvh3P9ar5WvEoXtVOl2gqQMM9XCu96Piy5pWOK7ZpjqO8pGqx5Psr+6GQBzhJrrU8BC6NHh62DqD+OL4+wWxZMNUQVlARU95flvAYG3JDjJBWToKQ=
